# Generated by Django 3.2.4 on 2021-07-12 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.TextField(verbose_name='장르')),
                ('playtime', models.IntegerField(verbose_name='상영시간')),
                ('date', models.TextField(verbose_name='개봉시기')),
                ('age', models.IntegerField(verbose_name='연령등급')),
                ('score_npro', models.IntegerField(verbose_name='네티즌평점중요도')),
                ('score_pro', models.IntegerField(verbose_name='전문가평점중요도')),
                ('score_gender', models.IntegerField(verbose_name='같은성별평점중요도')),
                ('score_age', models.IntegerField(verbose_name='같은연령평점중요도')),
                ('production', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='연출중요도')),
                ('acting', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='연기중요도')),
                ('story', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='스토리중요도')),
                ('visual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='영상미중요도')),
                ('ost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ost중요도')),
                ('reult_list', models.TextField(blank=True, null=True, verbose_name='결과리스트')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL, verbose_name='설문자')),
            ],
        ),
    ]
