# Generated by Django 3.2.4 on 2021-07-12 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL, verbose_name='설문자'),
        ),
    ]
