# Generated by Django 3.2.4 on 2021-07-13 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0003_remove_score_total'),
        ('recommend', '0002_alter_survey_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='유사도')),
                ('total', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='총점')),
                ('movie', models.ForeignKey(db_column='movie', on_delete=django.db.models.deletion.CASCADE, related_name='recommend', to='movie.movie', verbose_name='영화')),
                ('survey', models.ForeignKey(db_column='survey', on_delete=django.db.models.deletion.CASCADE, related_name='recommend', to='recommend.survey', verbose_name='설문조사')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='recommend', to=settings.AUTH_USER_MODEL, verbose_name='설문자')),
            ],
        ),
    ]
