# Generated by Django 3.2.4 on 2021-07-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='total'),
        ),
    ]
