# Generated by Django 3.2.4 on 2021-07-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_score_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='total',
        ),
    ]
